language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
branches: 
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: Wjf+xRncP/DmUl/aHIPTx8Pi+6BGiDhA3twNXVpBgSOlqSYQDqK3tOrsIGnMZ69cspa3SxE6TBre+lCwhm5i9Gfpvufu4hqYAJdsjrmmavIMZkXf9/qYW2KjH8LLwi+8D2OAg3KtsTzvoTs90fcvCBynyPI7BmyC8h9gC4l8GHoYiEzOQB5wUM1jWSXSLOYo8JQKL5A1r4V+Qp8BtA/IbwOAY+z5biGBreH/AvGwtw3+ABw8ZpNY9PQXnIJO56P++LVYCK/WyUBQlGNsM2Luz5+bjcmtKwelDfKTBaubCuLvAipr1jfP2/8miqKkXhPGsVxDldygteBRN5Est/v3Lh0GNjz6GWjCV6RgpeAK48g0FKe4KoXHVVsHjbFlMJ2PKy/VKN486LdYTAticEiUfqR7UpcZGvLDwsDGwzEd+mDsnbqmq0GElrBIi4vMxgZQfUbZUpeM2ql2Lk+dw4HTIaK5n5nBBoFjICHtgY+bBsrrhRPRB05z2WWkvNjd6cpqbWG5WDErlzrcRejwJLU29vjjb+MBd3mYbFzFHbYvpfsYd3G5yqZA3ZmU+Sx59cK2XWLcIlX2Pd1ApKlnlq9L/h62IuQ2YIDSi8rYfFvf5vf+fQQ+bPs9s7BQMOT0k4O8RRpJoq9npmR2+nshHh6/fYSkJkxpmhyHdwgU9+liGEQ=
