language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
branches: 
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: njeetO2lB/inNuDTBakkL0QJQC0dpRT4Rm2428eF8BoxrTBrpDtFvZAjWRxJukl5g2kagFuamRMvM5OR10OfXcsz7qQrYDJcqfgnn6uFIDLqmaS4jewbcjnlzHvBJBHhbtgGHNNnG2fhCcOOckApQaEBLSNOyA2qUHci3MoIqaiPHMR9NXdGiJBTCESeSKyNatQ50i5g8B3Y346LZyABueV0/h4/evmHW0LW27HiyB+dG89/NVRXKVfbCB/r8/2Fa7x38Y4mC9m8n/C4sR/Qi8Oo00HhHjSNu7jB/dVXTn1MLiMEObXz/sqVFibrUNZhBxHlt+JHQhIgSZgWxs2gxbqhKr9u2+h4qCiB2+4WvKxx77FmupClBzFQrBSyJausP0qb51yzOF8i40zJ4q5luEJDtiVciyBJNudlHhuDl83886XKFc1NeDcTGMHfSl7ulN8blXoKlxKQ/gntrfFeYoJY0HJsPVC1HfZb6bw1P2Isq9fp/22QnZu1yBIwUnDAM1JyPW68dj+saftnsoS13L8x5oNCtw9RImjM+zOWLAHSZYdmxzvmvP64Hn9QcQrPhu4UktU5z2cxcT1tOvQ+MXK2z6JaVWzICjSN5c9D5jA3VBh5Hlhu4TovSdT7uqqApwcLGHdfO/a7NhNp8/0EwN74wsn0lgPZ1NExHZXYCaQ=
